FROM harbor-test.haier.net/s02154/mtranserver-core:v1
# FROM docker.xuanyuan.me/xnuo/mtranserver:2.1.0
# docker.1ms.run/xnuo/mtranserver:2.1.0
# FROM docker.1ms.run/xnuo/mtranserver:latest

# # 复制models目录
COPY ./models /app/models

# # 复制应用代码
# COPY . .

# 保持端口暴露
# EXPOSE 3000 
